pipeline {

    parameters {
    
        booleanParam(defaultValue : false , description : 'Production Environment' , name : 'Production' )
        booleanParam(defaultValue : false , description : 'MOT Environment' , name : 'mot' )
        choice(name : 'Service' , choices : ['test' , 'test1' , 'dev' , 'dev-test'] , description : 'Select Application Service')
        choice( name : 'All' , choices : ['dev-test'] , description : 'Select All Services')
    
    }

    agent any

    tools {nodejs "node"}

    stages {
        

        stage("build") {

            steps {

                echo "${params.Production}"
                cd '../NodeJS_API_Automation/API Automation/package.json'
                bat 'npm install'

            }
        }
        stage("test") {

            steps {

                echo "${params.mot}"
                echo "${params.Service}"
                
            }
        }

    }
}

